# Generated by Django 4.2 on 2025-08-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alcoholproduct',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='alcoholproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='alcoholproduct',
            name='strength',
        ),
    ]
