# Generated by Django 4.2 on 2025-08-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_alcoholproduct_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcoholproduct',
            name='name',
            field=models.CharField(default='Без названия', max_length=255, verbose_name='Наименование'),
        ),
    ]
