# Generated by Django 4.2 on 2025-08-25 07:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alcoholproduct_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Предложения от поставщиков по продукту', 'verbose_name_plural': 'Предложения от поставщиков по продуктам'},
        ),
        migrations.CreateModel(
            name='PriceAlcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('alcohol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alcoholproduct')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
            options={
                'verbose_name': 'Предложения от поставщиков по алкоголю',
                'verbose_name_plural': 'Предложения от поставщиков по алкоголю',
                'unique_together': {('alcohol', 'supplier', 'date_added')},
            },
        ),
    ]
