# Generated by Django 4.2 on 2025-08-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_price_options_pricealcohol'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='type',
            field=models.CharField(choices=[('prod', 'Продукты'), ('alco', 'Алкоголь')], default='prod', max_length=20, verbose_name='Тип'),
        ),
    ]
