# Generated by Django 4.2 on 2025-08-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_supplier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(choices=[('prod', 'Продукты'), ('alco', 'Алкоголь'), ('all', 'Универсальный')], default='prod', max_length=20, verbose_name='Тип'),
        ),
    ]
