# Generated by Django 4.2 on 2025-08-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_supplier_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('boevka', 'Напитки Боевка'), ('grocery', 'Бакалея'), ('desserts', 'Десерты'), ('ice', 'Заморозка ММ'), ('milk', 'Молочка'), ('sh', 'СХ'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип'),
        ),
    ]
