# Generated by Django 4.2 on 2025-08-26 11:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliertoken',
            options={'verbose_name': 'Токен поставщика', 'verbose_name_plural': 'Токен поставщиков'},
        ),
        migrations.AlterField(
            model_name='alcoholproduct',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='price',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='price',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='price',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Предложенная цена'),
        ),
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='price',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='pricealcohol',
            name='alcohol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alcoholproduct', verbose_name='Алкоголь'),
        ),
        migrations.AlterField(
            model_name='pricealcohol',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='pricealcohol',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='pricealcohol',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='pricealcohol',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Предложенная цена'),
        ),
        migrations.AlterField(
            model_name='pricealcohol',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='inn',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Неверный формат ИНН', regex='^\\d{10,12}$')], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='suppliertoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='suppliertoken',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier', verbose_name='Наименование поставщика'),
        ),
        migrations.AlterField(
            model_name='suppliertoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Неверный формат номера телефона', regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='PriceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение/Комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('responded', 'Ответ получен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('alcohol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.alcoholproduct', verbose_name='Алкоголь')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='Продукт')),
                ('purchaser', models.ForeignKey(limit_choices_to={'role__in': ['purchaser', 'chief_purchaser', 'admin']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Закупщик')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Запрос цены',
                'verbose_name_plural': 'Запросы цен',
                'ordering': ['-created_at'],
            },
        ),
    ]
